### ISSUE TITLE
Missing google-services.json file

### ISSUE THREAD

**Issue by viini42** [OBrunoVieira/Covid-19-Android#3]
This is the configuration file from Firebase project.

PS: Also, the `kotlin-gradle-plugin` version should be `3.6.3`, the last stable version supported by the Android Studio 3.6.3 (last stable release)

**Comment by OBrunoVieira** [comment]
Hey @viniciusalmada, we do not commit the official `google-services.json` for security reasons. If you want to compile and run the project, please, remove firebase's dependencies and its references.

Regards :)
